### ISSUE TITLE
Uninstall method

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway-addon-python#90] opened 2021-03-01 10:01 UTC
Addon already have a very useful `unload` method that is called when they are disabled. I wonder, would it be an idea to have an 'uninstall' method that is called when an addon is uninstalled? Then it could quickly remove some files from `.webthings/data`.

**Comment by mrstegeman** [comment] 2021-03-01 19:03
Duplicate of https://github.com/WebThingsIO/gateway/issues/2062

**Closed as completed by mrstegeman** 2021-03-01 19:03 UTC

**Comment by flatsiedatsie** [comment] 2021-03-02 08:20
Apologies. I'm starting to forget the things I asked for earilier.. I'll do a better search next time.
